import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { fetchCategories } from "../http";
import { ICategory, ICollectionResponse } from "../types";
import { AxiosResponse } from "axios";
import Tabs from "../components/Tabs";

interface IPropTypes {
    categories: {
        items: ICategory[];
    };
}

const Home: NextPage<IPropTypes> = ({ categories }) => {
    console.log("Client side home ✅", categories);
    return (
        <div className={styles.container}>
            <Head>
                <title>NextJS Blog Homepage</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <Tabs categories={categories.items} />
            <main>
                <h1 className="text-3xl text-primary-dark">Home Page</h1>
            </main>
        </div>
    );
};

export const getServerSideProps = async () => {
    console.log("Server side home ✅");

    // categories
    const { data: categories } = await fetchCategories();

    return {
        props: {
            categories: {
                items: categories.data,
            },
        },
    };
};

export default Home;
